/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.5-dev */

#include "message.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(b_status_msg, b_status_msg, AUTO)


PB_BIND(b_mode_msg, b_mode_msg, AUTO)


PB_BIND(b_params_msg, b_params_msg, AUTO)




